# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3fdafbb90c7bcb7d25c296a4d1b4b4d0ae21eba2a2cba7e294120766dc26611bef7420fa2d4e8caae6dafa5af99df15a40eada4ba50f27ee0b47c060fca43c27

test:
  secret_key_base: a59ae96986b3a78c50045da3f5f05a790d97590abd21933240444a614c42e61a65c8a0a9dfd3e98618b1bdae0dbaccf281c1802c6d1c7e4aa48748d72678ed3d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
