source 'https://rubygems.org'

gem 'rails', '4.2.4'
gem 'pg'
gem 'responders', '2.1.2'
gem 'rack-cors', :require => 'rack/cors'
gem 'thin', '1.6.4'

group :development, :test do
  # Call 'byebug' anywhere in the code to stop execution and get a debugger console
  gem 'byebug'
  gem 'rspec-rails', '~> 3.4.2'
  gem 'pry'
end

group :development do
  # Access an IRB console on exception pages or by using <%= console %> in views
  gem 'web-console', '~> 2.0'

  # Spring speeds up development by keeping your application running in the background. Read more: https://github.com/rails/spring
  gem 'spring'
end

group :test do
  gem 'shoulda-matchers'
  gem 'capybara'
  gem 'simplecov', :require => false
end
